CFLAGS=		-W -Wall -fno-stack-protector -zexecstack
LDFLAGS=	-N -zexecstack

all: $(PROG) check shellcode

$(PROG): $(PROG).o
	$(LD) $(LDFLAGS) -o $@ $<

%.o: %.asm
	nasm $(NASMFLAGS) -f elf32 -o $@ $^

check: $(PROG)
	@objdump -dM intel $(PROG)|tail -n+7
	@asm-size $(PROG)
	@asm-opcodes $(PROG)

.PHONY: clean
clean:
	-rm -f $(PROG) *.o *.dot *.png *.strace
	-rm -f shellcode
ifneq (,$(wildcard ./$(PROG).asm.in))
	-rm -f $(PROG).asm
endif

count: $(PROG)
	@asm-opcodes $(PROG)|head -n1

sctest: $(PROG)
	@asm-sctest $(PROG)

shellcode: $(PROG)
	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ $(SKELETON)

strace: $(PROG)
	@strace -o $(PROG).strace ./shellcode
